from __future__ import annotations

from netlist_agent.ir import Const, Direction, GateType, NetBit
from netlist_agent.parser import parse_verilog
from netlist_agent.writer import write_verilog
from tests.helpers import assert_structurally_equal


def _write(tmp_path, name: str, content: str) -> str:
    path = tmp_path / name
    path.write_text(content)
    return str(path)


def test_bus_port_shared_declaration(tmp_path) -> None:
    src = """
    module top(a, b, c, y);
      input [7:0] a, b, c;
      output [7:0] y;
      buf g0(y, a);
    endmodule
    """
    path = _write(tmp_path, "bus_port.v", src)
    design = parse_verilog(path)

    assert [p.name for p in design.ports] == ["a", "b", "c", "y"]
    for name in ("a", "b", "c", "y"):
        sig = design.signals[name]
        assert (sig.msb, sig.lsb) == (7, 0)
    assert design.signals["a"].direction == Direction.INPUT
    assert design.signals["y"].direction == Direction.OUTPUT

    out_path = str(tmp_path / "bus_port_out.v")
    write_verilog(design, out_path)
    design2 = parse_verilog(out_path)
    assert_structurally_equal(design, design2)


def test_port_redeclared_as_wire_merges(tmp_path) -> None:
    src = """
    module top(n0, n4);
      input n0;
      output [15:0] n4;
      wire [15:0] n4;
      buf g0(n4[0], n0);
    endmodule
    """
    path = _write(tmp_path, "redecl.v", src)
    design = parse_verilog(path)

    assert list(design.signals.keys()).count("n4") == 1
    sig = design.signals["n4"]
    assert sig.direction == Direction.OUTPUT
    assert (sig.msb, sig.lsb) == (15, 0)

    out_path = str(tmp_path / "redecl_out.v")
    write_verilog(design, out_path)
    design2 = parse_verilog(out_path)
    assert_structurally_equal(design, design2)


def test_dff_with_bitselected_pins(tmp_path) -> None:
    src = """
    module top(n0, n1, busin, busout);
      input n0, n1;
      input [7:0] busin;
      output [7:0] busout;
      wire [7:0] n49;
      dff g0(.RN(n1), .SN(1'b1), .CK(n0), .D(n49[2]), .Q(busout[3]));
    endmodule
    """
    path = _write(tmp_path, "dff_bitsel.v", src)
    design = parse_verilog(path)

    gate = design.gates[0]
    assert gate.gate_type == GateType.DFF
    assert gate.pins["D"] == NetBit("n49", 2)
    assert gate.pins["Q"] == NetBit("busout", 3)
    assert gate.pins["SN"] == Const.ONE
    assert gate.pins["RN"] == NetBit("n1", None)
    assert gate.pins["CK"] == NetBit("n0", None)

    out_path = str(tmp_path / "dff_bitsel_out.v")
    write_verilog(design, out_path)
    design2 = parse_verilog(out_path)
    assert_structurally_equal(design, design2)


def test_constant_tied_to_gate_input(tmp_path) -> None:
    src = """
    module top(a, y);
      input a;
      output y;
      and g0(y, a, 1'b0);
    endmodule
    """
    path = _write(tmp_path, "const_tie.v", src)
    design = parse_verilog(path)

    gate = design.gates[0]
    assert gate.pins["I0"] == NetBit("a", None)
    assert gate.pins["I1"] == Const.ZERO

    out_path = str(tmp_path / "const_tie_out.v")
    write_verilog(design, out_path)
    design2 = parse_verilog(out_path)
    assert_structurally_equal(design, design2)


def test_line_comments_are_stripped(tmp_path) -> None:
    src = """
    // Generated by Some Tool
    // Verification Directory fv/top

    module top(a, b, y);
      input a, b; // two scalar inputs
      output y;
      // instantiate a single gate
      and g0(y, a, b);
    endmodule
    """
    path = _write(tmp_path, "comments.v", src)
    design = parse_verilog(path)

    assert design.module_name == "top"
    assert [p.name for p in design.ports] == ["a", "b", "y"]
    assert len(design.gates) == 1
    gate = design.gates[0]
    assert gate.gate_type == GateType.AND
    assert gate.pins["O"] == NetBit("y", None)
    assert gate.pins["I0"] == NetBit("a", None)
    assert gate.pins["I1"] == NetBit("b", None)

    out_path = str(tmp_path / "comments_out.v")
    write_verilog(design, out_path)
    design2 = parse_verilog(out_path)
    assert_structurally_equal(design, design2)
